version: '3'
services:
  api_application:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    image: alba2020/php
    container_name: api_application
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command:
      "php-fpm"
    networks:
      - backend_net

  queue_fake:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    image: alba2020/php
    container_name: queue_fake
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command:
      "php artisan queue:work --queue=fake"
    networks:
      - backend_net

  #Nginx Service
  api_webserver:
    image: nginx:alpine
    container_name: api_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - backend_net
  
  db_mysql:
    image: mysql:5.7.22
    container_name: db_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: smm_api
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
