<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Constants extends Model
{
    const INSTAGRAM = 'INSTAGRAM';
    const VK = 'VK';
    const FAKE = 'FAKE';
    const NOT_SET = 'NOT_SET';

    const SERVICE_INSTAGRAM_SUBS = 'SERVICE_INSTAGRAM_SUBS';

    const SERVICE_INSTAGRAM_LIKES = 'SERVICE_INSTAGRAM_LIKES';
    const SERVICE_INSTAGRAM_LIKES_LIVE = 'SERVICE_INSTAGRAM_LIKES_LIVE';

    const SERVICE_INSTAGRAM_VIEWS_IGTV = 'SERVICE_INSTAGRAM_VIEWS_IGTV';
    const SERVICE_INSTAGRAM_VIEWS_VIDEO = 'SERVICE_INSTAGRAM_VIEWS_VIDEO';
    const SERVICE_INSTAGRAM_VIEWS_VIDEO_IMPRESSIONS = 'SERVICE_INSTAGRAM_VIEWS_VIDEO_IMPRESSIONS';
    const SERVICE_INSTAGRAM_VIEWS_STORY = 'SERVICE_INSTAGRAM_VIEWS_STORY';
    const SERVICE_INSTAGRAM_VIEWS_SHOW_IMPRESSIONS = 'SERVICE_INSTAGRAM_VIEWS_SHOW_IMPRESSIONS';
    const SERVICE_INSTAGRAM_VIEWS_LIVE = 'SERVICE_INSTAGRAM_VIEWS_LIVE';

    const SERVICE_INSTAGRAM_AUTO_LIKES = 'SERVICE_INSTAGRAM_AUTO_LIKES';
    const SERVICE_INSTAGRAM_AUTO_LIKES_VIEWS_IMPRESSIONS = 'SERVICE_INSTAGRAM_AUTO_LIKES_VIEWS_IMPRESSIONS';
    const SERVICE_INSTAGRAM_AUTO_VIEWS = 'SERVICE_INSTAGRAM_AUTO_VIEWS';

    const subclasses = [
        self::SERVICE_INSTAGRAM_SUBS => \App\Orders\Subscribers::class,

        self::SERVICE_INSTAGRAM_LIKES => \App\Orders\Likes::class,
        self::SERVICE_INSTAGRAM_LIKES_LIVE => \App\Orders\LikesLive::class,

        self::SERVICE_INSTAGRAM_VIEWS_IGTV => \App\Orders\ViewsIGTV::class,
        self::SERVICE_INSTAGRAM_VIEWS_VIDEO => \App\Orders\ViewsVideo::class,
        self::SERVICE_INSTAGRAM_VIEWS_VIDEO_IMPRESSIONS => \App\Orders\ViewsVideoImpressions::class,
        self::SERVICE_INSTAGRAM_VIEWS_STORY => \App\Orders\ViewsStory::class,
        self::SERVICE_INSTAGRAM_VIEWS_SHOW_IMPRESSIONS => \App\Orders\ViewsShowImpressions::class,
        self::SERVICE_INSTAGRAM_VIEWS_LIVE => \App\Orders\ViewsLive::class,

        self::SERVICE_INSTAGRAM_AUTO_LIKES => \App\Orders\AutoLikes::class,
        self::SERVICE_INSTAGRAM_AUTO_LIKES_VIEWS_IMPRESSIONS => \App\Orders\AutoLikesViewsImpressions::class,
        self::SERVICE_INSTAGRAM_AUTO_VIEWS => \App\Orders\AutoViews::class,
    ];
}
