<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Constants extends Model
{
    const INSTAGRAM = 'INSTAGRAM';
    const VK = 'VK';
    const FAKE = 'FAKE';
    const NOT_SET = 'NOT_SET';

    const SERVICE_INSTAGRAM_LIKES = 'SERVICE_INSTAGRAM_LIKES';
    const SERVICE_INSTAGRAM_SUBS = 'SERVICE_INSTAGRAM_SUBS';
    const SERVICE_INSTAGRAM_VIDEO_VIEWS = 'SERVICE_INSTAGRAM_VIDEO_VIEWS';
    const SERVICE_INSTAGRAM_STORY_VIEWS = 'SERVICE_INSTAGRAM_STORY_VIEWS';

    const SERVICE_INSTAGRAM_AUTOLIKES = 'SERVICE_INSTAGRAM_AUTOLIKES';
    const SERVICE_INSTAGRAM_AUTOLIKES_IMPRESSIONS = 'SERVICE_INSTAGRAM_AUTOLIKES_IMPRESSIONS';
    const SERVICE_INSTAGRAM_AUTOSUBS = 'SERVICE_INSTAGRAM_AUTOSUBS';
    const SERVICE_INSTAGRAM_AUTOSUBS_IMPRESSIONS = 'SERVICE_INSTAGRAM_AUTOSUBS_IMPRESSIONS';

    const SERVICE_INSTAGRAM_IGTV_VIEWS = 'SERVICE_INSTAGRAM_IGTV_VIEWS';
    const SERVICE_INSTAGRAM_VIDEO_VIEWS_IMPRESSIONS = 'SERVICE_INSTAGRAM_VIDEO_VIEWS_IMPRESSIONS';
    const SERVICE_INSTAGRAM_LIVE_BROADCAST_VIEWERS = 'SERVICE_INSTAGRAM_LIVE_BROADCAST_VIEWERS';

    const SERVICE_AUTO_FAKE = 'SERVICE_AUTO_FAKE';

    const subclasses = [
        self::SERVICE_INSTAGRAM_LIKES => \App\Orders\Likes::class,
        self::SERVICE_INSTAGRAM_SUBS => \App\Orders\Subscribers::class,
        self::SERVICE_INSTAGRAM_VIDEO_VIEWS => \App\Orders\VideoViews::class,
        self::SERVICE_INSTAGRAM_STORY_VIEWS => \App\Orders\StoryViews::class,

        self::SERVICE_INSTAGRAM_AUTOLIKES => \App\Orders\AutoLikes::class,
        self::SERVICE_INSTAGRAM_AUTOLIKES_IMPRESSIONS => \App\Orders\AutoLikesImpressions::class,
        self::SERVICE_INSTAGRAM_AUTOSUBS => \App\Orders\AutoSubs::class,
        self::SERVICE_INSTAGRAM_AUTOSUBS_IMPRESSIONS => \App\Orders\AutoSubsImpressions::class,

        self::SERVICE_INSTAGRAM_IGTV_VIEWS => \App\Orders\IGTVViews::class,
        self::SERVICE_INSTAGRAM_VIDEO_VIEWS_IMPRESSIONS => \App\Orders\VideoViewsImpressions::class,
        self::SERVICE_INSTAGRAM_LIVE_BROADCAST_VIEWERS => \App\Orders\LiveBroadcastViewers::class,

        self::SERVICE_AUTO_FAKE => \App\Orders\AutoFake::class,
    ];
}
